#!/bin/bash

sxhkd &
urxvtd &

# Wallpaper
feh --bg-center --no-xinerama ~/Pictures/Wallpapers/hawk1080.png

#xrandr --output HDMI1 --primary --auto

# Desktops
bspc monitor HDMI1 -d I II III IV V VI VII VIII IX
#bspc monitor eDP1 -d I II III IV V VI VII VIII IX

# Appearance
bspc config window_gap 15
bspc config focused_border_color '#98971a'
bspc config presel_feedback_color '#88a522'
bspc config pointer_modifier super
bspc config click_to_focus on
bspc config borderless_monocle on
bspc config gapless_monocle on
bspc config single_monocle on
bspc config remove_disabled_monitors on
bspc config merge_overlapping_monitors on

# Window rules
bspc rule -a "Firefox" desktop=^1 private=on
bspc rule -a "Gimp" state=floating

yabar &
