#!/bin/bash

STATUS=$(cat /sys/class/power_supply/ACAD/online)
BAT=$(cat /sys/class/power_supply/BAT1/capacity)

if [ $STATUS -eq 1 ]; then
	ICON=""
	COLOR="668800"
elif [ $BAT -lt 10 ]; then
	ICON=""
	COLOR="FF0000"
elif [ $BAT -lt 30 ]; then
	ICON=""
	COLOR="FF8800"
elif [ $BAT -lt 70 ]; then
	ICON=""
	COLOR="ddaa00"
elif [ $BAT -lt 90 ]; then
	ICON=""
	COLOR="668800"
else
	ICON=""
	COLOR="668800"
fi
echo "%{+u U#$COLOR O10} $ICON $BAT% %{O10 -u U-}"
