#!/bin/bash

PANEL_FIFO="/tmp/statusbar.fifo"
PANEL_DIR="/home/andrei/.config/lemonbar"

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

# Time
while true; do
	#echo T"$(date +' %{c O10}  %_H:%M %{O10} %{r O10}  %a, %d %b %{O10}')"
	echo T"$(date +' %{O10}  %_H:%M %{O10}')"
	sleep 60
done > "$PANEL_FIFO" &

# Battery
while true; do
	echo B"$($PANEL_DIR/battery)"
	sleep 30
done > "$PANEL_FIFO" &

# Network
while true; do
	echo N"$($PANEL_DIR/network)"

	sleep 60
done > "$PANEL_FIFO" &

# Volume
echo V"$($PANEL_DIR/volume)" > "$PANEL_FIFO" &

# Headset
#acpi_listen | awk '/jack\/headphone HEADPHONE/{print $3}' | \
#	while read -r line; do
#		"$PANEL_DIR/update_volume"
#	done &

# MPD
while true; do
	echo M"%{O10} $($PANEL_DIR/mpd_status) %{O10}"
	sleep 5
done > "$PANEL_FIFO" &

# Bspwm desktops
bspc subscribe report > "$PANEL_FIFO" &

# Get screen width
PANEL_WIDTH=$(xrandr | grep '*' | grep -Po "\d+x" | grep -Po "\d+")

< "$PANEL_FIFO" "$PANEL_DIR/panel_print" | lemonbar \
	-g         "$PANEL_WIDTH"x30+0+0 \
	-n         "top_panel" \
	-B         "#ca282828" \
	-F         "#ffffff" \
	-u         4 \
	-f         "ypn envypn:pixelsize=16" \
	-f         "Inconsolata" \
	-f         "FontAwesome"

wait
