#!/bin/bash

UF="#668800"
Uf=""
PAD=""
while read -r line; do
	case $line in
		B*)
			# Battery
			battery="$PAD${line#?}$PAD"
			;;
		N*)
			# Network
			network="$PAD${line#?}$PAD"
			;;
		W*)
			# Desktops
			desktops=""
			IFS=":"
			set -- ${line#?}
			while [ $# -gt 0 ]; do
				item=$1
				name=${item#?}
				case $item in
					[OF]*)
						# focused desktop
						desktops="$desktops%{O4}%{O4}"
						;;
					o*)
						# occupied unfocused desktop
						desktops="$desktops%{O4}%{O4}"
						;;
					f*)
						# free unfocused desktop
						desktops="$desktops%{O4}%{O4}"
				esac
				shift
			done

			desktops="$PAD${desktops}$PAD"
			;;
		T*)
			# Time
			datetime="$PAD${line#?}$PAD"
			;;
		V*)
			# Volume
			volume="$PAD${line#?}$PAD"
			;;
		M*)
			# MPD
			mpd="$PAD${line#?}$PAD"
			;;
	esac
	printf "%s\n" "%{l}${datetime}${battery}${network}%{c}${desktops}%{r}${volume}${mpd}"
done
