#!/bin/bash

MUTED=$( pamixer --get-mute )

ICON=""
COLOR="#668800"

if [ $MUTED == "true" ]; then
	ICON=""
	COLOR="#FF0000"
fi

VOL=$( pamixer --get-volume )

echo "%{+u U$COLOR O10} $ICON $VOL %{O10 -u U-}"
