#!/bin/zsh

# Start sxhkd if not running
if [ ! $(pgrep sxhkd) != "" ]; then
	sxhkd & #> $HOME/.config/sxhkd/log
fi
#urxvtd &

# Appearance
bspc config window_gap 0
bspc config border_width 2
bspc config focused_border_color '#d79921'
bspc config presel_feedback_color '#d79921'

bspc config borderless_monocle on
bspc config gapless_monocle on
bspc config single_monocle on

# Behaviour
#bspc config pointer_modifier super
bspc config click_to_focus on

bspc config remove_disabled_monitors on
bspc config merge_overlapping_monitors on

bspc config initial_polarity second_child

#
#bspc config external_rules_command ~/.config/bspwm/rules
#
## Window rules
#bspc rule -a "Firefox" desktop=^1 private=on
bspc rule -a "fontforge" state=floating
bspc rule -a "feh" state=floating
bspc rule -a '*':"scratchpad" sticky=on state=floating
bspc rule -a "jetbrains-studio" desktop=focused:^2
bspc rule -a "jetbrains-phpstorm" desktop=focused:^2
bspc rule -a "discord" desktop=focused:^5
bspc rule -a "Pavucontrol" state=floating
bspc rule -a "Zathura" state=tiled

# Monitor
xrandr --output HDMI-1 --auto --primary --preferred \
	--output eDP-1 --auto --left-of HDMI-1

# Desktops
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9
bspc monitor --focus HDMI-1

## Monitor
#MONITOR=$(xrandr | grep -Po "(?<=HDMI-1\s)(dis)*connected")
#if [ "$MONITOR" == "connected" ]; then
#	xrandr --output eDP1 --off
#fi

# Wallpaper
~/.fehbg

# Compton
compton &

# Redshift
redshift &

urxvtd &

# Panel
$PANEL_DIR/panel_info &
sleep 1
$PANEL_DIR/panel &
