#!/bin/bash
ICON=""

# Device states
# Ethernet
if [ $(cat "/sys/class/net/enp8s0/operstate") == "up" ]; then
	ICON=""
	INFO=$(ip addr show enp8s0 | grep -Po "inet (\d+\.*){4}" | grep -Po "[\d+.]{4}" | tr -d '\n')
fi

# USB
if nmcli device show enp0s20f0u2 &> /dev/null; then
	ICON=""
	INFO=$(ip addr show enp0s20f0u2 | grep -Po "inet (\d+\.*){4}" | grep -Po "[\d+.]{4}" | tr -d '\n')
fi

# Wireless
if [ $(cat "/sys/class/net/wlp7s0/operstate") == "up" ]; then
	ICON="$ICON"
	INFO=$(nmcli device show wlp7s0 | awk '/GENERAL.CONNECTION:/ {print $2}')
fi

# Format
if [ "$ICON" == "" ]; then
	echo "%{F#ff0000} down %{F-}"
else
	echo "$ICON $INFO"
fi
