#!/bin/sh

# Start sxhkd if not running
if [ ! $(pgrep sxhkd) != "" ]; then
	sxhkd &
fi
#urxvtd &

# Appearance
bspc config window_gap 0
bspc config border_width 3
bspc config focused_border_color '#98971a'
bspc config presel_feedback_color '#88a522'
bspc config pointer_modifier super
bspc config click_to_focus on
bspc config borderless_monocle on
bspc config gapless_monocle on
bspc config single_monocle on
bspc config remove_disabled_monitors on
bspc config merge_overlapping_monitors on
#
#bspc config external_rules_command ~/.config/bspwm/rules
#
## Window rules
#bspc rule -a "Firefox" desktop=^1 private=on
bspc rule -a "fontforge" state=floating
bspc rule -a "feh" state=floating
bspc rule -a "Termite":"scratchpad" sticky=on
#
## Desktops
bspc monitor -d 1 2 3 4 5 6 7 8 9
#bspc monitor eDP1 -d I II III IV V VI VII VIII IX
#
## Monitor
MONITOR=$(xrandr | grep "HDMI1" | grep -Po "[dis]*connected")
if [ "$MONITOR" == "connected" ]; then
	xrandr --output eDP1 --off
fi
#
## Wallpaper
~/.fehbg
#
## Compton
#compton &
#
## Redshift
redshift &
#
## Panel
~/.config/lemonbar/panel_info &
