#!/bin/zsh

ICON_COLOR="#a2a5aa"
function icon {
    local end_color=${2:-"-"}
    echo "%{F$ICON_COLOR}$1%{F$end_color}"
}

UF="#668800"
Uf=""
PAD="%{O10}"
ACCENT_COLOR="#d79921"
CURRENT_FG_COLOR="-"
CURRENT_BG_COLOR="-"
desktop_icons=(        )
while read -r line; do
    case $line in
        T*)
            # Time
            datetime="$PAD${line#?}$PAD"
            ;;
        B*)
            # Battery
            battery="$PAD${line#?}$PAD"
            ;;
        N*)
            # Network
            network="$PAD${line#?}$PAD"
            ;;
        W*)
            # Desktops
            desktops=""
            items=( "${(@s/:/)line#?}" )
            for item in $items; do
                name=${item:1}
                case $item in
                    [Mm]*)
                        MON_INDEX=$(( $(bspc query --names -M | grep -n $name | cut -d ':' -f 1) - 1 ))
                        desktops="$desktops%{S$MON_INDEX}"

                        case $item in
                            M*)
                                desktops="$desktops%{F-}"
                                CURRENT_FG_COLOR='-'
                                CURRENT_BG_COLOR='-'
                                ;;
                            m*)
                                CURRENT_FG_COLOR='#555'
                                CURRENT_BG_COLOR='#444'
                                desktops="$desktops unfocused %{F#555}"
                                ;;
                        esac
                        ;;
                    O*)
                        # focused desktop
                        desktops="$desktops%{F$ACCENT_COLOR} ${desktop_icons[$name]} %{F$CURRENT_FG_COLOR}"
                        ;;
                    o*)
                        # occupied unfocused desktop
                        desktops="$desktops ${desktop_icons[$name]} "
                        ;;
                esac
            done

            ;;
        V*)
            # Volume
            volume="$PAD${line#?}$PAD"
            ;;
        "jack/headphone HEADPHONE "*)
            # Headphones
            $PANEL_DIR/update_volume
            ;;
        player*)
            # MPD
            mpd="$($PANEL_DIR/mpd_status)"
            ;;
    esac
    printf "%s\n" "%{Sl}%{l}${desktops}%{F-}${mpd}%{c}${datetime}%{r}%{Sl} ${volume} ${network} ${battery}"
done
